// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: infxbc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetUserV01Request struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetUserV01Request) Reset()         { *m = QueryGetUserV01Request{} }
func (m *QueryGetUserV01Request) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserV01Request) ProtoMessage()    {}
func (*QueryGetUserV01Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_08482179575a03e0, []int{0}
}
func (m *QueryGetUserV01Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserV01Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserV01Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserV01Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserV01Request.Merge(m, src)
}
func (m *QueryGetUserV01Request) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserV01Request) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserV01Request.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserV01Request proto.InternalMessageInfo

func (m *QueryGetUserV01Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetUserV01Response struct {
	UserV01 *UserV01 `protobuf:"bytes,1,opt,name=UserV01,proto3" json:"UserV01,omitempty"`
}

func (m *QueryGetUserV01Response) Reset()         { *m = QueryGetUserV01Response{} }
func (m *QueryGetUserV01Response) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserV01Response) ProtoMessage()    {}
func (*QueryGetUserV01Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_08482179575a03e0, []int{1}
}
func (m *QueryGetUserV01Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserV01Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserV01Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserV01Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserV01Response.Merge(m, src)
}
func (m *QueryGetUserV01Response) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserV01Response) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserV01Response.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserV01Response proto.InternalMessageInfo

func (m *QueryGetUserV01Response) GetUserV01() *UserV01 {
	if m != nil {
		return m.UserV01
	}
	return nil
}

type QueryAllUserV01Request struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUserV01Request) Reset()         { *m = QueryAllUserV01Request{} }
func (m *QueryAllUserV01Request) String() string { return proto.CompactTextString(m) }
func (*QueryAllUserV01Request) ProtoMessage()    {}
func (*QueryAllUserV01Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_08482179575a03e0, []int{2}
}
func (m *QueryAllUserV01Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUserV01Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUserV01Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUserV01Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUserV01Request.Merge(m, src)
}
func (m *QueryAllUserV01Request) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUserV01Request) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUserV01Request.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUserV01Request proto.InternalMessageInfo

func (m *QueryAllUserV01Request) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllUserV01Response struct {
	UserV01    []*UserV01          `protobuf:"bytes,1,rep,name=UserV01,proto3" json:"UserV01,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUserV01Response) Reset()         { *m = QueryAllUserV01Response{} }
func (m *QueryAllUserV01Response) String() string { return proto.CompactTextString(m) }
func (*QueryAllUserV01Response) ProtoMessage()    {}
func (*QueryAllUserV01Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_08482179575a03e0, []int{3}
}
func (m *QueryAllUserV01Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUserV01Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUserV01Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUserV01Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUserV01Response.Merge(m, src)
}
func (m *QueryAllUserV01Response) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUserV01Response) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUserV01Response.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUserV01Response proto.InternalMessageInfo

func (m *QueryAllUserV01Response) GetUserV01() []*UserV01 {
	if m != nil {
		return m.UserV01
	}
	return nil
}

func (m *QueryAllUserV01Response) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetUserV01Request)(nil), "infx.infxbc.infxbc.QueryGetUserV01Request")
	proto.RegisterType((*QueryGetUserV01Response)(nil), "infx.infxbc.infxbc.QueryGetUserV01Response")
	proto.RegisterType((*QueryAllUserV01Request)(nil), "infx.infxbc.infxbc.QueryAllUserV01Request")
	proto.RegisterType((*QueryAllUserV01Response)(nil), "infx.infxbc.infxbc.QueryAllUserV01Response")
}

func init() { proto.RegisterFile("infxbc/query.proto", fileDescriptor_08482179575a03e0) }

var fileDescriptor_08482179575a03e0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0x3a, 0x41,
	0x14, 0xc7, 0x9d, 0xfd, 0xfd, 0x2a, 0x98, 0xa0, 0xc3, 0x10, 0x15, 0x5a, 0x8b, 0x6c, 0x54, 0x62,
	0x30, 0x93, 0x46, 0xe7, 0xb0, 0x43, 0x5e, 0x4d, 0xa8, 0x43, 0xa7, 0x76, 0x75, 0xda, 0x06, 0xd6,
	0x9d, 0xd5, 0x99, 0x8d, 0x24, 0xba, 0x74, 0x8c, 0x0e, 0x41, 0xa7, 0xce, 0xfd, 0x33, 0x1d, 0x85,
	0x2e, 0x1d, 0x43, 0xfb, 0x43, 0xc2, 0x99, 0xd1, 0xb4, 0x15, 0xf3, 0xa4, 0xbc, 0xf9, 0x7e, 0xdf,
	0xf7, 0xf3, 0xf6, 0x3d, 0x88, 0x58, 0x78, 0x79, 0xe3, 0xd5, 0x48, 0x33, 0xa6, 0xad, 0x36, 0x8e,
	0x5a, 0x5c, 0x72, 0xa4, 0x6a, 0x58, 0x3f, 0x98, 0x9f, 0xf4, 0xba, 0xcf, 0xb9, 0x1f, 0x50, 0xe2,
	0x46, 0x8c, 0xb8, 0x61, 0xc8, 0xa5, 0x2b, 0x19, 0x0f, 0x85, 0x76, 0xa4, 0xf3, 0x35, 0x2e, 0x1a,
	0x5c, 0x10, 0xcf, 0x15, 0x54, 0xb7, 0x22, 0xd7, 0x05, 0x8f, 0x4a, 0xb7, 0x40, 0x22, 0xd7, 0x67,
	0xa1, 0x12, 0x1b, 0xed, 0xb2, 0x49, 0x8c, 0x05, 0x6d, 0x9d, 0xed, 0x15, 0x74, 0xd5, 0xc9, 0xc1,
	0x95, 0x93, 0xbe, 0xaf, 0x4c, 0xe5, 0xa9, 0x7e, 0xa8, 0xd2, 0x66, 0x4c, 0x85, 0x44, 0x4b, 0xd0,
	0x62, 0xf5, 0x35, 0x90, 0x05, 0xb9, 0xff, 0x55, 0x8b, 0xd5, 0x9d, 0x0a, 0x5c, 0x4d, 0x28, 0x45,
	0xc4, 0x43, 0x41, 0xd1, 0x01, 0x5c, 0x30, 0x25, 0xa5, 0x5f, 0x2c, 0x66, 0x70, 0x72, 0x14, 0x3c,
	0x70, 0x0d, 0xb4, 0xce, 0x85, 0xc9, 0x2e, 0x05, 0xc1, 0xaf, 0xec, 0x63, 0x08, 0x7f, 0xf8, 0x4d,
	0xcf, 0x6d, 0xac, 0x87, 0xc5, 0xfd, 0x61, 0xb1, 0xfe, 0x6e, 0x66, 0x58, 0x5c, 0x71, 0x7d, 0x6a,
	0xbc, 0xd5, 0x11, 0xa7, 0xf3, 0x02, 0x0c, 0xf4, 0x68, 0xc4, 0x24, 0xe8, 0x7f, 0xb3, 0x42, 0xa3,
	0xf2, 0x18, 0x9a, 0xa5, 0xd0, 0x76, 0xfe, 0x44, 0xd3, 0x99, 0xa3, 0x6c, 0xc5, 0x57, 0x0b, 0xce,
	0x29, 0x36, 0xf4, 0x08, 0x86, 0x28, 0x28, 0x3f, 0x09, 0x62, 0xf2, 0x86, 0xd2, 0xbb, 0x33, 0x69,
	0x75, 0xb4, 0x93, 0xbb, 0x7f, 0xff, 0x7a, 0xb6, 0x1c, 0x94, 0x25, 0x7d, 0x21, 0x31, 0xc7, 0x30,
	0x7e, 0x13, 0xe4, 0x96, 0xd5, 0xef, 0xd0, 0x03, 0x80, 0xd0, 0xb8, 0x4b, 0x41, 0x30, 0x85, 0x28,
	0xb1, 0xb7, 0x29, 0x44, 0xc9, 0x05, 0x38, 0x9b, 0x8a, 0x68, 0x03, 0x65, 0xa6, 0x10, 0x1d, 0x1d,
	0xbe, 0x75, 0x6d, 0xd0, 0xe9, 0xda, 0xe0, 0xb3, 0x6b, 0x83, 0xa7, 0x9e, 0x9d, 0xea, 0xf4, 0xec,
	0xd4, 0x47, 0xcf, 0x4e, 0x9d, 0x6f, 0xf9, 0x4c, 0x5e, 0xc5, 0x1e, 0xae, 0xf1, 0xc6, 0x58, 0x83,
	0xe1, 0x1f, 0xd9, 0x8e, 0xa8, 0xf0, 0xe6, 0xd5, 0x9d, 0xef, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x24, 0x63, 0x51, 0x34, 0x71, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a userV01 by id.
	UserV01(ctx context.Context, in *QueryGetUserV01Request, opts ...grpc.CallOption) (*QueryGetUserV01Response, error)
	// Queries a list of userV01 items.
	UserV01All(ctx context.Context, in *QueryAllUserV01Request, opts ...grpc.CallOption) (*QueryAllUserV01Response, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) UserV01(ctx context.Context, in *QueryGetUserV01Request, opts ...grpc.CallOption) (*QueryGetUserV01Response, error) {
	out := new(QueryGetUserV01Response)
	err := c.cc.Invoke(ctx, "/infx.infxbc.infxbc.Query/UserV01", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserV01All(ctx context.Context, in *QueryAllUserV01Request, opts ...grpc.CallOption) (*QueryAllUserV01Response, error) {
	out := new(QueryAllUserV01Response)
	err := c.cc.Invoke(ctx, "/infx.infxbc.infxbc.Query/UserV01All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a userV01 by id.
	UserV01(context.Context, *QueryGetUserV01Request) (*QueryGetUserV01Response, error)
	// Queries a list of userV01 items.
	UserV01All(context.Context, *QueryAllUserV01Request) (*QueryAllUserV01Response, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) UserV01(ctx context.Context, req *QueryGetUserV01Request) (*QueryGetUserV01Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserV01 not implemented")
}
func (*UnimplementedQueryServer) UserV01All(ctx context.Context, req *QueryAllUserV01Request) (*QueryAllUserV01Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserV01All not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_UserV01_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserV01Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserV01(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infx.infxbc.infxbc.Query/UserV01",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserV01(ctx, req.(*QueryGetUserV01Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserV01All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUserV01Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserV01All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infx.infxbc.infxbc.Query/UserV01All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserV01All(ctx, req.(*QueryAllUserV01Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infx.infxbc.infxbc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserV01",
			Handler:    _Query_UserV01_Handler,
		},
		{
			MethodName: "UserV01All",
			Handler:    _Query_UserV01All_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infxbc/query.proto",
}

func (m *QueryGetUserV01Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserV01Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserV01Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserV01Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserV01Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserV01Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UserV01 != nil {
		{
			size, err := m.UserV01.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllUserV01Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUserV01Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUserV01Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllUserV01Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUserV01Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUserV01Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserV01) > 0 {
		for iNdEx := len(m.UserV01) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserV01[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetUserV01Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetUserV01Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserV01 != nil {
		l = m.UserV01.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllUserV01Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllUserV01Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UserV01) > 0 {
		for _, e := range m.UserV01 {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetUserV01Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserV01Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserV01Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserV01Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserV01Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserV01Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserV01", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UserV01 == nil {
				m.UserV01 = &UserV01{}
			}
			if err := m.UserV01.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUserV01Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUserV01Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUserV01Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUserV01Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUserV01Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUserV01Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserV01", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserV01 = append(m.UserV01, &UserV01{})
			if err := m.UserV01[len(m.UserV01)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
